// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZnBAEn_LyS8B8RQjEOH_T_AXyNleitU',
    appId: '1:454100797190:web:8abeaba6d197a43f93c087',
    messagingSenderId: '454100797190',
    projectId: 'ws-fluttercookbook',
    authDomain: 'ws-fluttercookbook.firebaseapp.com',
    storageBucket: 'ws-fluttercookbook.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRmEGJSbzodeFjZ3JWrsJYminT9U2o9w',
    appId: '1:454100797190:android:d135052f4a5a5d5693c087',
    messagingSenderId: '454100797190',
    projectId: 'ws-fluttercookbook',
    storageBucket: 'ws-fluttercookbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtye9OHjoigXRLhdcZsxWPp9A2yux_5Bc',
    appId: '1:454100797190:ios:4978dcd2c122770093c087',
    messagingSenderId: '454100797190',
    projectId: 'ws-fluttercookbook',
    storageBucket: 'ws-fluttercookbook.appspot.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtye9OHjoigXRLhdcZsxWPp9A2yux_5Bc',
    appId: '1:454100797190:ios:4978dcd2c122770093c087',
    messagingSenderId: '454100797190',
    projectId: 'ws-fluttercookbook',
    storageBucket: 'ws-fluttercookbook.appspot.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGZnBAEn_LyS8B8RQjEOH_T_AXyNleitU',
    appId: '1:454100797190:web:f7d5d894f38930b793c087',
    messagingSenderId: '454100797190',
    projectId: 'ws-fluttercookbook',
    authDomain: 'ws-fluttercookbook.firebaseapp.com',
    storageBucket: 'ws-fluttercookbook.appspot.com',
  );

}